#Create a tag file just so Intune knows this was installed
If(-not(Test-Path -Path "$($env:ProgramData)\CXN\Scripts\CreateRDPShortcutToDesktop"))
    {
    New-Item -itemtype "directory" -path "$($env:ProgramData)\CXN\Scripts\CreateRDPShortcutToDesktop"
    Set-Content -Path "$($env:ProgramData)\CXN\Scripts\CreateRDPShortcutToDesktop\CreateRDPShortcutToDesktop.ps1.tag" -Value "Installed"
    }

#info over special folders in powershell: https://www.devguru.com/content/technologies/wsh/wshshell-specialfolders.html

$new_object = New-Object -ComObject WScript.Shell

#Hier de naam aanpassen van rdp file bij test.rdp

$destination = $new_object.SpecialFolders.Item("AllUsersDesktop") + "\CAS-RDS.rdp"
New-Item $destination

#Hieronder kunnen we de properties van de RDP bepalen, om de eigenschappen van een bestaande RDP te achterhalen kunnen we de RDP opendoen in Notepad
#Belangrijk, de eerste tick moet na $Destinatinon komen, niet eronder!!!!, de tweede tick achter de regel, dus ook niet eronder
#Script moet lopen in system/admin mode

Set-Content $destination 'redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:2
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:CAS-SRVBR01.CASIER.LOCAL
gatewayhostname:s:rdsgw.casier.com
workspace id:s:CAS-SRVBR01.Casier.local
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.RemoteDesktopCol
use multimon:i:1
alternate full address:s:CAS-SRVBR01.CASIER.LOCAL
signscope:s:Full Address,Alternate Full Address,Use Redirection Server Name,Server Port,GatewayHostname,GatewayUsageMethod,GatewayProfileUsageMethod,GatewayCredentialsSource,PromptCredentialOnce,RedirectDrives,RedirectPrinters,RedirectCOMPorts,RedirectSmartCards,RedirectClipboard,DevicesToRedirect,DrivesToRedirect,LoadBalanceInfo
signature:s:AQABAAEAAADEEwAAMIITwAYJKoZIhvcNAQcCoIITsTCCE60CAQExDzANBglghkgB  ZQMEAgEFADALBgkqhkiG9w0BBwGgghGzMIIFtjCCBJ6gAwIBAgIRALa0/kygbito  aJdkA0TTV7kwDQYJKoZIhvcNAQELBQAwgY8xCzAJBgNVBAYTAkdCMRswGQYDVQQI  ExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAOBgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoT  D1NlY3RpZ28gTGltaXRlZDE3MDUGA1UEAxMuU2VjdGlnbyBSU0EgRG9tYWluIFZh  bGlkYXRpb24gU2VjdXJlIFNlcnZlciBDQTAeFw0yMTAxMTAwMDAwMDBaFw0yMjAx  MjIyMzU5NTlaMBcxFTATBgNVBAMMDCouY2FzaWVyLmNvbTCCASIwDQYJKoZIhvcN  AQEBBQADggEPADCCAQoCggEBAN4zBeAe+oYjnvgUDt2tvLLCSOwfrRbFH3nmCPPz  tmutL+Ca2zH6X0mU3CYzxW3fnv/2sNSM8A1QkNrLGlqcXCtwRPZUiDKR6n0sXxZR  8yIYb5vHWpqIudimcA1p7MAbI2Ptq1jicjEIp+60avvgtSbemAYy+yrUzSYsAMBO  KwjISzeuHrDHHeM9yH4nHyfngxlPYElNlRoXqE3fEMn32wqeT8rJ6uwXOnphqO0w  Ux7sXNeVx3k6WyioaZM0JOUkU6nMX3UeEInfSJe4Myim2Q6IrXniT8ye5QPoaulw  rjz6E39U+VImhrobCTJFl60PqFW+8ISwMV7gxK+ryiF3pxsCAwEAAaOCAoIwggJ+  MB8GA1UdIwQYMBaAFI2MXsRUrYrhd+mb+ZsF4bgBjWHhMB0GA1UdDgQWBBS1PPsW  B8/CdkvTDaDhN94Zn6PZIjAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAd  BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwSQYDVR0gBEIwQDA0BgsrBgEE  AbIxAQICBzAlMCMGCCsGAQUFBwIBFhdodHRwczovL3NlY3RpZ28uY29tL0NQUzAI  BgZngQwBAgEwgYQGCCsGAQUFBwEBBHgwdjBPBggrBgEFBQcwAoZDaHR0cDovL2Ny  dC5zZWN0aWdvLmNvbS9TZWN0aWdvUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNl  cnZlckNBLmNydDAjBggrBgEFBQcwAYYXaHR0cDovL29jc3Auc2VjdGlnby5jb20w  IwYDVR0RBBwwGoIMKi5jYXNpZXIuY29tggpjYXNpZXIuY29tMIIBBgYKKwYBBAHW  eQIEAgSB9wSB9ADyAHcARqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcA  AAF27pZe+wAABAMASDBGAiEA+86yFNBVDZbQYVuXWOeczQ5HKj+EeBjL4Wc3bxPI  594CIQCmG6Z4toD7vKEyDVsU+D0Ka00337VG6gafKkk/U6UOBAB3AN+lXqtogk8f  bK3uuF9OPlrqzaISpGpejjsSwCBEXCpzAAABdu6WYEMAAAQDAEgwRgIhAPcAwlQf  ETuIv5ZXQAUeSbupvyovBRLc6asDGgCe7yl3AiEAt3Sfdt/pQVYE1kuPSNF93bLt  e+8pDS/+nApckf9h0rUwDQYJKoZIhvcNAQELBQADggEBAEuh6ndNsJjFr/oYJ5oe  ALNmL+exnJKRdqUdEbQkSIvdJFtIUYqHulyusy5OuMkvTOeLiKIyuquWEyUssNKC  kxggHJxYWKRvVC/nS+2tp7RHoHj2Uh2N14/OvBQ7oxmfclC4nkboqbYIf8XtcyJ7  1/x9aQvpmpBBJFHTWfy9Wf/wELL8HmgvpSzkRm6zcS6IrcqvPw9elovYHldl16+/  EKcG2ugECZSMPWAENcm6JkKBrPkCix1/v0+c7J7n7h2t8UobPoV8tGX6pWvqW7x+  TKvnxMpFE3lkP42jlrfK7aZoKxFT3zZ8nC2ftRpYMHb4c9ztMnr/Edb3ZMm17YnB  CkQwggXeMIIDxqADAgECAhAB/W0w/KPKUagbvGQONQMtMA0GCSqGSIb3DQEBDAUA  MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKTmV3IEplcnNleTEUMBIGA1UEBxML  SmVyc2V5IENpdHkxHjAcBgNVBAoTFVRoZSBVU0VSVFJVU1QgTmV0d29yazEuMCwG  A1UEAxMlVVNFUlRydXN0IFJTQSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAeFw0x  MDAyMDEwMDAwMDBaFw0zODAxMTgyMzU5NTlaMIGIMQswCQYDVQQGEwJVUzETMBEG  A1UECBMKTmV3IEplcnNleTEUMBIGA1UEBxMLSmVyc2V5IENpdHkxHjAcBgNVBAoT  FVRoZSBVU0VSVFJVU1QgTmV0d29yazEuMCwGA1UEAxMlVVNFUlRydXN0IFJTQSBD  ZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC  AgoCggIBAIASZRc2DsPbCLPQrFcNdu3NJ9NMrVCDYeKqIE0JLWQJ3M6Jn8w9qez2  z8Hc8dOx1ns3KBErR9o5xrw6GbRfpr19naNjQrZ28qk7K5H44m/Q7BYgkAk+4uh0  yRi0kdRiZNt/owbxiBhqkCI8vP4T8IcUe/bkH47U5FHGEWdGCFHLhhRUP7wz/n5s  nP8WnRi9UY41pqdmyHJn2yFmsdSbeAPAUDrozPDcvJ5M/q8FljUfV1q3/875Pbcs  tvZU3cjnEjpNrkyKt1yatLcgPcp/IjSufjtoZgFE5wFORlObM2D3lL5TN5BzQ/My  w1Pv26r+dE5px2uMYJPexMcM3+EyrsyTO1F4lWeL7j1W/gzQaQ8bD/MlJmszbfdu  R/pzQ+V+DqVmsSl8MoRjVYnEDcGTVDAZE6zTfTen6106bDVc20HXEtqpSQvf2ICK  CZNijrVmzyWIzYS4sT+kOQ/ZAp7rEkyVfPNrBaleFoPMuGfi6BOdzFuC00yz7Vv/  3uVzrCM7LQC/NVV0CUnYSVgaf5I25lGSDvMmfRxNF7zJ7EMm0L9BX0CpRET0medX  h55QH1dUqD79dGMvsVBlCeZYQi5DGky08CVHWfoEHpPUJkZKUIGy3r54t/xnFeHJ  V4QeD2PW6WK61l9VLupcxigIBCU5uA4rqfJMlxwHPw1S9e3vL4IPAgMBAAGjQjBA  MB0GA1UdDgQWBBRTeb9aqitKz1SA4dibwJ3ysgNmyzAOBgNVHQ8BAf8EBAMCAQYw  DwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQwFAAOCAgEAXNR8Dc/3AX1BmWUM  c8VSn8v4z5kGfxvaQxWfngJVV5YU8VI8J4eUKO0fOgE3onb8U1DAhJvGa066jCFP  oo5VYpHzaRXYvIjjxKoL/e+o6UtVKgYgbVV4KRnuXzBcSyQRVf8kmm5eKivuC02f  f/cBOJQUlUMHCftgqe4cqxKMoJpep5hqWW2LPwj7yNFFrxgVZJASD3MoLsXiJE78  WOzw9EX+IrPrL47S2UVhBcGXb6h2co+LjDavvw0FznGN5qZvH2ymcWLF2NCDcgzx  ZxGJDJwTTHI037zVcd+qcd3huWyMPBJdZdq9VxK2Q2v/5d5NZhFRz5mu7Be26HGR  jN5J/t01caIVJ5Qcz2HjJrtvo2clIV3m3R0LLmgbO4Kv7INnhdSYUXSxuZmAif9/  eBlceUpgLpJArkw3KizJx2LIDl33NlvK4CUlAbTdGgecdwA/0NzV7D3U+rs/zIXW  b3+pLd+5Avf1l5q1NdrDZ7CHSqkoniOO/1wna+GwT/MH7gAu1FmHy1JBler0R9fu  ZEFVfI1ZApXdYp3Cue5aKHSEpZu3kMcMB9/1iTZ0MtYowbCwC+CcTMMc1vzjabVH  RoEvooKr02NEcMSN/y0zuq2Pe7VwiK4+Gc9AKNj8yJC7XZki9VLmWMUfiDFD7ogd  18aOPENqHacY3n09FvFi+cqQqP0wggYTMIID+6ADAgECAhB9W1EmtHa6Edt0Fgu8  Uw2nMA0GCSqGSIb3DQEBDAUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKTmV3  IEplcnNleTEUMBIGA1UEBxMLSmVyc2V5IENpdHkxHjAcBgNVBAoTFVRoZSBVU0VS  VFJVU1QgTmV0d29yazEuMCwGA1UEAxMlVVNFUlRydXN0IFJTQSBDZXJ0aWZpY2F0  aW9uIEF1dGhvcml0eTAeFw0xODExMDIwMDAwMDBaFw0zMDEyMzEyMzU5NTlaMIGP  MQswCQYDVQQGEwJHQjEbMBkGA1UECBMSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYD  VQQHEwdTYWxmb3JkMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0ZWQxNzA1BgNVBAMT  LlNlY3RpZ28gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIgQ0Ew  ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDWczPW1zwg0ADSF0W41j4H  oj/HQe4yMMmwbP30n8sSmA8tP41NAQyCDxd/Yi7puEh5+xaDTq3XMiWTtwe/uVA/  qUzDQCrpOf/ZgcofFjJB2oAmuSN6hyAe4/8gmjyVRG+HdQaQQLQykxYJEAgjPtLd  hw9vXVEUagppxU8BcmnP05NMbQSgoxuCfrGaue3FnsU3eJ+aCDT7Vi5YxAkOBmRb  vDfc8Z8oaKhWsJKjXJ+7iJgIGyQdqzCFrq+wLp56ncHAQhziAvDq4ErS75AOtMFA  FvBvhUJKZPekMKD+vy6jJ1qOi1i4rcMZF4Rj7W9W/YPLYDTEdL7mndvh5OXKDF8V  AgMBAAGjggFuMIIBajAfBgNVHSMEGDAWgBRTeb9aqitKz1SA4dibwJ3ysgNmyzAd  BgNVHQ4EFgQUjYxexFStiuF36Zv5mwXhuAGNYeEwDgYDVR0PAQH/BAQDAgGGMBIG  A1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC  MBsGA1UdIAQUMBIwBgYEVR0gADAIBgZngQwBAgEwUAYDVR0fBEkwRzBFoEOgQYY/  aHR0cDovL2NybC51c2VydHJ1c3QuY29tL1VTRVJUcnVzdFJTQUNlcnRpZmljYXRp  b25BdXRob3JpdHkuY3JsMHYGCCsGAQUFBwEBBGowaDA/BggrBgEFBQcwAoYzaHR0  cDovL2NydC51c2VydHJ1c3QuY29tL1VTRVJUcnVzdFJTQUFkZFRydXN0Q0EuY3J0  MCUGCCsGAQUFBzABhhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMA0GCSqGSIb3  DQEBDAUAA4ICAQAyv2G9DkjDT8e6R034nHgZAdwTHYBv/MNwtFKaMTOaV1L7MZ5r  pO9UqomNQBdo+BEQfNLKsfFVhsfuszaRhvY5Ub9Gvw+gurT3fknEKjYXnuRoOXqv  lE5Wb7J7O78Khr3NxXccA7g4saIfX37bitxGSLZoCs+ytbTiNORnqThmCV7SuPyd  KDoXQCfCck4p/SE8fM8T+5YsxTFE/RPt1ZupaWh3fO7h/6T5NjgIUzmihDScGfO+  DqzVJDfrI6h40NPn75JHZGI5Iu/G9xG+IoXGZkQkJo4QMo3Ik64HnoM+L9n59UaO  Y77B5rTcps0hqIYKldkuhSYa/fyxtldCbZXRM/Y5FAaCQTj1j1jcgFuk1X2VeP2n  m//9xahpqybnp6QFh1upt7ijIAuXqUWF3bOL5Yk3jikN/AYX9jhADkLkEgb7e/PG  EWhi3+OY9BPYFU+LsWnZEGC8ZCrqMbfktaM6FJsm4wt7/QKOtpnBOJdZNvaodKKG  tl7rxmTqz6Cj+W6eui0RtoaYCFgtyawlZPJedbQ4wa5/WkaD6lHKtvGZETVrpWp7  xgCw5/i+ZLKtyMLxrONR6qST4HnI4YFAyQpb4RI8wWAq45fAiULKlM9GmBJpu5jQ  wtMNcktHbuWTxDIoY4dD5LAyPgrTS78jmxQpQSuaBB+TLfHHOUg8rVoSfzGCAdEw  ggHNAgEBMIGlMIGPMQswCQYDVQQGEwJHQjEbMBkGA1UECBMSR3JlYXRlciBNYW5j  aGVzdGVyMRAwDgYDVQQHEwdTYWxmb3JkMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0  ZWQxNzA1BgNVBAMTLlNlY3RpZ28gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3Vy  ZSBTZXJ2ZXIgQ0ECEQC2tP5MoG4raGiXZANE01e5MA0GCWCGSAFlAwQCAQUAMA0G  CSqGSIb3DQEBAQUABIIBAC4+RXBmVHpwyyiqgBQo9dS2z8cN3xunFCVHN4LwTSes  wBz79iXDHcHXfohJHpcmpl4MgFuEHTWR5JMULkT2zuPMqmzzuNO7fo2Qa4AXGZjo  umriZrp1mQQXeekM2k453uAs+QJqvD+mw9SfbTpXGO4sA0wl98/Or5kbosCO92WP  8owMBHAODqb2va0PetYLndNtY04zc6v9Wm6wLY8VQpA6QftIhYXierHWlqpxUSZP  LGSF51nuu3ztGW51N3lEjjSUNBIhcAFlcHACY98tw3n0NMyB3CjiTSf/Xmi91QU2  ALSsMoiIJKPGl6EN5WThL1c5ZMbp/O18kBgOREerSV0='  

    
    

